(deftheme agg-light
  "Created 2024-08-17.")

(custom-theme-set-faces
 'agg-light
 '(default ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :height 98 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#655370" :background "#fbf8ef" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#100a14"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight normal :foreground "#3a81c3" :inherit (bold)))))
 '(highlight ((t (:foreground "#655370" :background "#d3d3e7"))))
 '(region ((t (:extend t :background "#ffcc80"))))
 '(shadow ((t (:foreground "#a094a2"))))
 '(secondary-selection ((t (:extend t :background "#e3dedd"))))
 '(trailing-whitespace ((t (:background "#e0211d"))))
 '(font-lock-bracket-face ((t (:foreground "#7c7f93"))))
 '(font-lock-builtin-face ((t (:foreground "#3a81c3"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (shadow)))))
 '(font-lock-comment-face ((t (:slant normal :foreground "#2aa1ae" :background "#ecf3ec" :inherit (shadow)))))
 '(font-lock-constant-face ((t (:foreground "#4e3163"))))
 '(font-lock-delimiter-face ((t (:foreground "#7c7f93"))))
 '(font-lock-doc-face ((t (:foreground "#da8b55" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:foreground "#ea76cb"))))
 '(font-lock-function-call-face ((t (:foreground "#1e66f5"))))
 '(font-lock-function-name-face ((t (:foreground "#6c3163" :inherit (bold)))))
 '(font-lock-keyword-face ((t (:slant normal :foreground "#3a81c3" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#4e3163"))))
 '(font-lock-number-face ((t (:foreground "#fe640b"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t (:foreground "#04a5e5"))))
 '(font-lock-preprocessor-face ((t (:foreground "#6c3163"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#d20f39"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d20f39"))))
 '(font-lock-string-face ((t (:foreground "#2d9574"))))
 '(font-lock-type-face ((t (:foreground "#ba2f59" :inherit (bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#715ab1"))))
 '(font-lock-variable-use-face ((t (:foreground "#4c4f69"))))
 '(font-lock-warning-face ((t (:foreground "#dc752f" :background "#fbf8ef" :inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line :position nil) :foreground "#2aa1ae"))))
 '(link-visited ((t (:underline (:color foreground-color :style line :position nil) :foreground "#6c4173"))))
 '(fringe ((t (:foreground "#655370" :background "#fbf8ef"))))
 '(header-line ((t (:background "#efeae9" :inherit (mode-line)))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#655370" :background "#c8c6dd"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color nil :style released-button) :foreground "#655370" :background "#e7e5eb"))))
 '(mode-line-buffer-id ((t (:foreground "#6c3163" :inherit (bold)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color nil :style released-button) :inverse-video nil :foreground "#655370" :background "#fbf8ef"))))
 '(isearch ((t (:weight bold :foreground "#fbf8ef" :background "#ba2f59" :inherit (match)))))
 '(isearch-fail ((t (:inherit (error)))))
 '(lazy-highlight ((t (:foreground "#5c5f77" :background "#dae6d0"))))
 '(match ((t (:foreground "#ba2f59" :background "#d3d3e7"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'agg-light)
