;; common env config
(require 'agg-aggressive-indent)
;;(require 'agg-auto-complete)
;; (require 'agg-ac-emacs-eclim)
;; (require 'agg-ac-js2)
(require 'agg-bar-cursor)
(require 'agg-bundler)
(require 'agg-browse-url)
;; (require 'agg-chruby)
(require 'agg-cider)
(require 'agg-clojure-mode)
(require 'agg-css)
;; (require 'agg-company-emacs-eclim)
;; (require 'agg-company-tern)
(require 'agg-company)
;; (require 'agg-eclim)
;; (require 'agg-ensime)
;; (require 'agg-erc)
;; (require 'agg-erc-hipchatify)
(require 'agg-flycheck)
(require 'agg-flycheck-clojure)
;; (require 'agg-flycheck-purescript)
(require 'agg-html-mode)
(require 'agg-ido-mode)
(require 'agg-ido-vertical-mode)
(require 'agg-ido-completing-read-+)
(require 'agg-js2-mode)
(require 'agg-json-mode)
(require 'agg-json-reformat)
(require 'agg-markdown-mode)
;; (require 'agg-markdown-preview-eww)
(require 'agg-magit)
(require 'agg-nxml-mode)
(require 'agg-org-mode)
(require 'agg-projectile)
(require 'agg-psc-ide)
(require 'agg-psci)
;; (require 'agg-purescript-mode)
(require 'agg-restclient)
(require 'agg-ruby-mode)
;; (require 'agg-robe)
;; (require 'agg-saveplace)
;; (require 'agg-sbt-mode)
;; (require 'agg-scala-mode)
(require 'agg-shell-mode)
(require 'agg-smex)
(require 'agg-sql-mode)
(require 'agg-tern)
(require 'agg-tidy)
(require 'agg-tramp)
(require 'agg-uniquify)
(require 'agg-yaml-mode)
(require 'agg-yari)

(provide 'agg-env)
