name: check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - uses: leotaku/elisp-check@master
      with:
        check: load-file
        file: init.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
    - uses: leotaku/elisp-check@master
      with:
        check: byte-compile
        file: init.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
